version: '3.2'

services:
  web:
    build:
      context: .
      cache_from:
        - ${DOCKER_IMAGE}:${BRANCH_TAG}
      args:
        - BUILD_ENV=development
        - RUBY_ENV=development
    image: ${DOCKER_IMAGE}:${BRANCH_TAG}
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true
    volumes:
      - ruby-bundle:/bundle
      - .:/app
    environment:
      - RACK_ENV=development
      - RAILS_ENV=development

volumes:
  ruby-bundle:
